sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tCHyWucEaU16n7mPbZ6
    accessKeySecret: 0nHgAQxhUyLgX7IySsV5atQ0CUKd3v
    bucketName: sky-take-out249